# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt


    role_hierarchy:
        ROLE_PROPRIO:       ROLE_USER
        ROLE_LOCATAIRE:       ROLE_USER
        ROLE_REFERENT:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        #main:
        #    pattern: ^/
        #    form_login:
        #        provider: fos_userbundle
        #        csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
        #    logout:       true
        #    anonymous:    true

        main:
            pattern:    ^/
            form_login:
                #check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                default_target_path: after_login
            logout:
                path:   /logout
                target: /login
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /new$, roles: [ROLE_ADMIN,ROLE_REFERENT,ROLE_PROPRIO ]}
        - { path: ^/validation$, role: ROLE_ADMIN }
        
        - { path: ^/, role: ROLE_USER }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }








